-- Phase 2B: rules for rides posted by drivers.

-- Ids are generated by the database, clients never choose them.
alter table public.rides alter column id set default gen_random_uuid()::text;

-- Business rules that hold for every row (the demo rides satisfy them).
alter table public.rides
  add constraint rides_price_range_check check (price_per_seat between 50 and 5000),
  add constraint rides_seats_total_range_check check (seats_total between 1 and 6),
  add constraint rides_duration_range_check check (duration_mins between 15 and 1440),
  add constraint rides_from_city_check check (char_length(trim(from_city)) between 2 and 60),
  add constraint rides_to_city_check check (char_length(trim(to_city)) between 2 and 60),
  add constraint rides_cities_differ_check check (lower(trim(from_city)) <> lower(trim(to_city))),
  add constraint rides_pickup_check check (char_length(trim(pickup_point)) between 3 and 80),
  add constraint rides_drop_check check (char_length(trim(drop_point)) between 3 and 80),
  add constraint rides_car_model_check check (char_length(trim(car_model)) between 2 and 40),
  add constraint rides_car_color_check check (char_length(trim(car_color)) between 2 and 40);

-- Clients may only write the form columns. id, is_demo, demo_*, seats_left and created_at are never writable.
revoke insert, update on public.rides from authenticated;

grant insert (
  driver_id, from_city, to_city, pickup_point, drop_point, departure_time, duration_mins,
  price_per_seat, seats_total, car_model, car_color, pref_ac, pref_music, pref_pets, pref_luggage
) on public.rides to authenticated;

grant update (
  from_city, to_city, pickup_point, drop_point, departure_time, duration_mins,
  price_per_seat, seats_total, car_model, car_color, pref_ac, pref_music, pref_pets, pref_luggage
) on public.rides to authenticated;

-- Only upcoming rides can be changed or deleted, so past rides stay as read only history.
drop policy "drivers update their own rides" on public.rides;
drop policy "drivers delete their own rides" on public.rides;

create policy "drivers update their own upcoming rides"
  on public.rides for update
  to authenticated
  using (driver_id = (select auth.uid()) and is_demo = false and departure_time > now())
  with check (driver_id = (select auth.uid()) and is_demo = false);

create policy "drivers delete their own upcoming rides"
  on public.rides for delete
  to authenticated
  using (driver_id = (select auth.uid()) and is_demo = false and departure_time > now());

-- Rules that cannot be a plain check constraint.
create function public.rides_enforce_rules()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Bookings arrive in a later phase. Until then every seat is free.
  new.seats_left := new.seats_total;

  -- Writes without a signed-in user (the service role, migrations) skip the rules below.
  if (select auth.uid()) is null then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if new.departure_time < now() + interval '1 hour' or new.departure_time > now() + interval '90 days' then
      raise exception 'ride_time_window';
    end if;
    if (
      select count(*)
      from public.rides r
      where r.driver_id = new.driver_id
        and not r.is_demo
        and r.departure_time > now()
    ) >= 10 then
      raise exception 'ride_limit_reached';
    end if;
  elsif new.departure_time is distinct from old.departure_time then
    if new.departure_time < now() + interval '1 hour' or new.departure_time > now() + interval '90 days' then
      raise exception 'ride_time_window';
    end if;
  end if;

  return new;
end;
$$;

create trigger rides_enforce_rules_trg
  before insert or update on public.rides
  for each row
  when (not new.is_demo)
  execute function public.rides_enforce_rules();

-- Same function as before, plus a nightly cleanup of rides posted from the shared demo account.
create or replace function public.refresh_demo_rides()
returns void
language sql
security definer
set search_path = ''
as $$
  update public.rides
  set departure_time =
    ((((now() at time zone 'Asia/Kolkata')::date + demo_day_offset) + demo_time) at time zone 'Asia/Kolkata')
  where is_demo
    and demo_day_offset is not null
    and demo_time is not null;

  delete from public.rides
  where not is_demo
    and driver_id in (select id from auth.users where email = 'demo@saathchalo.test');
$$;
